version: "3.3"

services:
  web:
    image: httpd
    ports:
      - "80:80"
    links:
      - fluentd
    logging:
      driver: "fluentd"
      options:
        fluentd-address: localhost:24224
        tag: httpd.access
        fluentd-async: "true"

  fluentd:
    build: ./fluentd
    volumes:
      - ./fluentd/conf:/fluentd/etc
    environment: 
      - ES_PASSWORD=$ES_PASSWORD
      - ES_USERNAME=$ES_USERNAME
      - SERVICE1=$SERVICE1
      - SERVICE1_PREFIX=$SERVICE1_PREFIX
      - HOST=$HOST
      - PORT=$PORT
      - SCHEME=$SCHEME
    links:
      - "elasticsearch"
    ports:
      - "24224:24224"
      - "24224:24224/udp"

  elasticsearch:
      build:
        context: elasticsearch/
        args:
          ELK_VERSION: $ELK_VERSION
      container_name: elasticsearch
      volumes:
        - type: bind
          source: ./elasticsearch/config/elasticsearch.yml
          target: /usr/share/elasticsearch/config/elasticsearch.yml
          read_only: true
        - type: volume
          source: esdata
          target: /usr/share/elasticsearch/data
      ulimits:
        memlock:
          soft: -1
          hard: -1
      ports:
        - "9200:9200"
        - "9300:9300"
      environment:
        - ES_JAVA_OPTS=-Xmx256m -Xms256m
        - ELASTIC_PASSWORD=$ES_PASSWORD
        - DISCOVERY_TYPE=$DISCOVERY_TYPE
        - CLUSTER_NAME=$CLUSTER_NAME
        - NETWORK_HOST=$NETWORK_HOST

  kibana:
    build:
      context: kibana/
      args:
        ELK_VERSION: $ELK_VERSION
    volumes:
      - type: bind
        source: ./kibana/config/kibana.yml
        target: /usr/share/kibana/config/kibana.yml
        read_only: true
    ports:
      - "5601:5601"
    links:
      - "elasticsearch"
    environment: 
      - ELASTICSEARCH_USERNAME=$ES_USERNAME
      - ELASTICSEARCH_PASSWORD=$ES_PASSWORD
      - HOST=$HOST
      - PORT=$PORT
      - SCHEME=$SCHEME
      - PUBLIC_BASE_URL=$PUBLIC_BASE_URL
      - KIBANA_SERVER_NAME=$KIBANA_SERVER_NAME

volumes:
  esdata:  