version: "3.8"

services:
  caddy:
    build:
      context: caddy/
      args:
        CADDY_VERSION: $CADDY_VERSION
    ports:
      - "80:80"
      - "443:443"
    environment: 
      - CADDY_INGRESS_NETWORKS=caddy
      - CADDY_DOCKER_CADDYFILE_PATH=/Caddyfile
      - BASE_WEB_ADDRESS=$CADDY_BASE_WEB_ADDRESS
      - OAUTH_REALM=$OAUTH_REALM
      - OAUTH_CLIENT=$OAUTH_CLIENT
      - OAUTH_SECRET=$OAUTH_SECRET
      - OAUTH_META_URL=$OAUTH_META_URL
      - OAUTH_BASE_URL=$OAUTH_BASE_URL
      - OAUTH_TOKEN=$OAUTH_TOKEN 
      - OAUTH_LOGOUT=$OAUTH_LOGOUT
    networks:
      - caddy
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - caddy_data:/data
      - ./Caddyfile:/Caddyfile     
    restart: unless-stopped  
    logging:
      driver: "fluentd"
      options:
        fluentd-address: $FLUENTD_ADDRESS
        tag: $CADDY_TAG
        fluentd-async: "true"

  fluentd:
    build: ./fluentd
    volumes:
      - ./fluentd/conf:/fluentd/etc
    environment: 
      - ES_PASSWORD=$ES_PASSWORD
      - ES_USERNAME=$ES_USERNAME
      - SERVICE1=$SERVICE1
      - SERVICE1_PREFIX=$SERVICE1_PREFIX
      - HOST=$HOST
      - PORT=$PORT
      - SCHEME=$SCHEME
      - CADDY_PREFIX=$CADDY_PREFIX
      - CADDY_TAG=$CADDY_TAG
    networks:
      - caddy
    links:
      - "elasticsearch"
    ports:
      - "24224:24224"
      - "24224:24224/udp"
    labels: 
      caddy: $FLUENTD_ADDRESS
      caddy.reverse_proxy: "{{upstreams 24224}}"

  elasticsearch:
      build:
        context: elasticsearch/
        args:
          ELK_VERSION: $ELK_VERSION
      container_name: elasticsearch
      volumes:
        - type: bind
          source: ./elasticsearch/config/elasticsearch.yml
          target: /usr/share/elasticsearch/config/elasticsearch.yml
          read_only: true
        - type: volume
          source: esdata
          target: /usr/share/elasticsearch/data
      ulimits:
        memlock:
          soft: -1
          hard: -1
      ports:
        - "9200:9200"
        - "9300:9300"
      environment:
        - ES_JAVA_OPTS=-Xmx1g -Xms1g
        - ELASTIC_PASSWORD=$ES_PASSWORD
        - DISCOVERY_TYPE=$DISCOVERY_TYPE
        - CLUSTER_NAME=$CLUSTER_NAME
        - NETWORK_HOST=$NETWORK_HOST
      networks:
        - caddy

  kibana:
    build:
      context: kibana/
      args:
        ELK_VERSION: $ELK_VERSION
    volumes:
      - type: bind
        source: ./kibana/config/kibana.yml
        target: /usr/share/kibana/config/kibana.yml
        read_only: true
    ports:
      - "5601:5601"
    links:
      - "elasticsearch"
    environment: 
      - ELASTICSEARCH_USERNAME=$ES_USERNAME
      - ELASTICSEARCH_PASSWORD=$ES_PASSWORD
      - HOST=$HOST
      - PORT=$PORT
      - SCHEME=$SCHEME
      - PUBLIC_BASE_URL=$PUBLIC_BASE_URL
      - PUBLIC_URL_SCHEME=$PUBLIC_URL_SCHEME  
      - KIBANA_SERVER_NAME=$KIBANA_SERVER_NAME
    networks:
      - caddy

networks:
  caddy:
    external: true
      
volumes:
  caddy_data: {}
  esdata:
