---
## Default Kibana configuration from Kibana base image.
## https://github.com/elastic/kibana/blob/master/src/dev/build/tasks/os_packages/docker_generator/templates/kibana_yml.template.ts
#
server.name: ${KIBANA_SERVER_NAME}
server.host: 0.0.0.0
server.publicBaseUrl: '${SCHEME}://${PUBLIC_BASE_URL}'
elasticsearch.hosts: [ "${SCHEME}://${HOST}:${PORT}" ]
monitoring.ui.container.elasticsearch.enabled: true